---
- name: Deploy Frontend (Uptime-Kuma)
  hosts: frontend
  become: yes
  vars:
    app_dir: /home/ubuntu/uptime-kuma
  tasks:
    - name: Ensure Docker is installed
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker service is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes


    - name: Install docker-compose
      ansible.builtin.apt:
        name: docker-compose
        state: present
        update_cache: yes

    - name: Clone frontend repo
      git:
        repo: 'https://github.com/mostafaibrahim24/uptime-kuma.git'
        dest: "{{ app_dir }}"
        version: master
        force: yes
    - name: Building..
      ansible.builtin.command:
        cmd: echo Building...
    - name: Run docker-compose up
      ansible.builtin.command:
        cmd: docker-compose -f docker-compose.yaml up -d
      args:
        chdir: "{{ app_dir }}"
